apiVersion: apps/v1
kind: Deployment
metadata:
  name: sort-app-deployment
spec:
  replicas: 3   # عدد الـ pods
  selector:
    matchLabels:
      app: sort-app
  template:
    metadata:
      labels:
        app: sort-app
    spec:
      containers:
        - name: sort-app-container
          image: younesaliyounes/sort-app:latest
          imagePullPolicy: Always
          stdin: true
          tty: true
